### ISSUE TITLE
"ESLint: TypeError: this.libOptions.parse is not a function" at aws-s3-image-upload

### ISSUE THREAD

**Issue by mkayander** [vercel/examples#393]
`ESLint: TypeError: this.libOptions.parse is not a function` error shows up in WebStorm when opening TS files.
This is related to the newest ESLint version 8.23.0 
It works fine with 8.22.0

**Comment by mkayander** [comment]
The reliable solution for now is to just set `"eslint": "8.22.0"` in package.json. I provided this fix in the linked PR.
